
services:
  db:
    image: mysql:8.0
    container_name: proyectofct-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectofct
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - fct-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: proyectofct-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fct-network

volumes:
  mysql_data:

networks:
  fct-network:
    driver: bridge